#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("El_juego_de_la_vida_android.Resource", IsApplication=true)]

namespace El_juego_de_la_vida_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int feliz = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int muerto = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int vivo = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050033
			public const int btngen_sus = 2131034163;
			
			// aapt resource value: 0x7f050032
			public const int btnn_gen = 2131034162;
			
			// aapt resource value: 0x7f050031
			public const int btnreiniciar = 2131034161;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int imageV1 = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int imageV10 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int imageV11 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int imageV12 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int imageV13 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int imageV14 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int imageV15 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int imageV16 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int imageV17 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int imageV18 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int imageV19 = 2131034131;
			
			// aapt resource value: 0x7f050002
			public const int imageV2 = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int imageV20 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int imageV21 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int imageV22 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int imageV23 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int imageV24 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int imageV25 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int imageV26 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int imageV27 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int imageV28 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int imageV29 = 2131034141;
			
			// aapt resource value: 0x7f050003
			public const int imageV3 = 2131034115;
			
			// aapt resource value: 0x7f05001e
			public const int imageV30 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int imageV31 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int imageV32 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int imageV33 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int imageV34 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int imageV35 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int imageV36 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int imageV37 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int imageV38 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int imageV39 = 2131034151;
			
			// aapt resource value: 0x7f050004
			public const int imageV4 = 2131034116;
			
			// aapt resource value: 0x7f050028
			public const int imageV40 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int imageV41 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int imageV42 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int imageV43 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int imageV44 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int imageV45 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int imageV46 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int imageV47 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int imageV48 = 2131034160;
			
			// aapt resource value: 0x7f050005
			public const int imageV5 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int imageV6 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int imageV7 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int imageV8 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int imageV9 = 2131034121;
			
			// aapt resource value: 0x7f050034
			public const int textView1 = 2131034164;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
